<a href="https://colab.research.google.com/github/Konikakonika/DATASCIENCE/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python3 --version

Python 3.10.11


In [ ]:
!sudo update-alteratives --config python3

sudo: update-alteratives: command not found


In [ ]:
print("hello world!")

hello world!


In [ ]:
x=12
y=12

In [ ]:
z=x+y

In [ ]:
print(z)

24


In [ ]:
type(z)

int

In [ ]:
x='hello'
type(x)

str

In [ ]:
x,y=10,20

In [ ]:
x,y=y,x

In [ ]:
x+y

30

In [ ]:
x-y

10

In [ ]:
x*y

200

In [ ]:
x/y

2.0

In [ ]:
x**2

400

In [ ]:
x**y

10240000000000

In [ ]:
x/y

2.0

In [ ]:
x//y

2

In [ ]:
8%4

0

In [ ]:
a=7
b=8
c=a+b
print(c)

15


In [ ]:
print("Sum is", c)

Sum is 15


In [ ]:
print("sum of",a,"and",b,"is",c)

sum of 7 and 8 is 15


In [ ]:
print("sum of %d"%c)
print("sum of %d and %d os %d"%(a,b,c))

sum of 15
sum of 7 and 8 os 15


In [ ]:
print("sum of {}".format(c))

sum of 15


In [ ]:
print("sum of {} and {} is {}".format(a,b,c))

sum of 7 and 8 is 15


In [ ]:
d=a/b
d

0.875

In [ ]:
print("div of {} and {} is {}".format(a,b,d))

div of 7 and 8 is 0.875


In [ ]:
print("div of {} and {} is {:.2f}".format(a,b,d))

div of 7 and 8 is 0.88


In [ ]:
print("sum of {} and {} is {}".format(c,a,b))

sum of 15 and 7 is 8


In [ ]:
print("sum of {1} and {2} is {0}".format(c,a,b))

sum of 7 and 8 is 15


In [ ]:
#f-strings=format string lierals
print(f"sum of {a} and {b} is {c}")

sum of 7 and 8 is 15


In [ ]:
c=a+b
d=a-b
e=a/b
f=a*b
print(f"1. add is{c}")
print(f"2. add is{d}")
print(f"3. add is{e}")
print(f"4. add is{f}")

1. add is15
2. add is-1
3. add is0.875
4. add is56


In [ ]:
print(f"""
1. add is {c}
2. sub is {d}
3. mul is {f}
""")#multiline print statement


1. add is 15
2. sub is -1
3. mul is 56



In [ ]:
a=10
b=10
c=a+b
print("sum is ",c)

sum is  20


In [ ]:
#a=10
#b=10
#c=a+b
#print("sum is ",c=a+b)#print m c naam ka operator nhi hoti chlega nhi code

In [ ]:
a=6
b=8
#walrus operator :=
print("sum is", c:=a+b)

sum is 14


In [ ]:
x=input("enter first no :")
y=input("enter sec no :")
z=x+y
print("sum is",z) # wrong ans becz input funct string hi written krta h

enter first no :6
enter sec no :7
sum is 67


In [ ]:
x=int(input("enter first no :"))
y=int(input("enter sec no :"))
z=x+y
print("sum is",z)

enter first no :7
enter sec no :6
sum is 13


In [ ]:
#control flow statement 
#loops
#-for
#-while

In [ ]:
for i in range(5): #indentatation error
  print(i)

0
1
2
3
4


In [ ]:
for i in range(3):
  print(i)

0
1
2


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,21,2):
  print(i,end=",")

1,3,5,7,9,11,13,15,17,19,

In [ ]:
for i in range(2,21,2):
  print(i,end=" ")

2 4 6 8 10 12 14 16 18 20 

In [ ]:
for i in range(2,21,2):
  print(i)

2
4
6
8
10
12
14
16
18
20


In [ ]:
for i in range(3):
  for j in range(3):
    print(i,j)
    print("*" * 10)

0 0
**********
0 1
**********
0 2
**********
1 0
**********
1 1
**********
1 2
**********
2 0
**********
2 1
**********
2 2
**********


In [ ]:
for i in range(10,1,-1):
  print(i)

10
9
8
7
6
5
4
3
2


In [ ]:
for i in range(1,6):
  print("*"*i)

*
**
***
****
*****


In [ ]:
for i in range(6,0,-1):
  print("*"*i)

******
*****
****
***
**
*


In [ ]:
for i in range(10):
  print(" "*(10-i)+"*"*(2*i+1))

          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************


In [ ]:
x=10
while x>0:
  print(x)
  x-=1

10
9
8
7
6
5
4
3
2
1


In [ ]:
x=10
while True:
  print(x)
  x -=1
  if x==1:
    break


10
9
8
7
6
5
4
3
2


In [ ]:
num=6
if num%2==0:
  print("no is even")
else:
    print("no id odd")

no is even


In [ ]:
if num%2==0: print("no is even")
else:
  print("no id odd")

no is even


In [ ]:
print("even") if num%2==0 else print("odd")

even


In [ ]:
x,y,z=10,20,30
if x>y and x>z:
  print("x is greatest")
elif y>z and y>x:
    print("y is greatest")
else:
      print("z is greatest")

z is greatest


In [ ]:
"x" if x>y and x>z else "y" if y>x and y>z else "z"

'z'

In [ ]:
#mini game -guess the no
import random

cpu= random.randint(1,100)
counter=5
while True:
  guess=int(input("guess the number:"))

  if cpu==guess:
    print("congrats, you guessed the correct no...")
  
    break
  elif guess>cpu:
    print("you guess is a greater number...")
  
  elif guess<cpu:
    print("you guess is a smaller number...")
  counter-=1
  print("chances left ::",counter)

  if counter==0:
    print("you lose the game..number was",cpu)
    break

guess the number:3
you guess is a smaller number...
chances left :: 4
guess the number:4
you guess is a smaller number...
chances left :: 3
guess the number:5
you guess is a smaller number...
chances left :: 2
guess the number:76
you guess is a greater number...
chances left :: 1
guess the number:78
you guess is a greater number...
chances left :: 0
you lose the game..number was 47


end of python from ravi sir video

**DATA SCIENCE**

In [ ]:
import numpy as np

In [ ]:
np.array([3,4,5,6,7,8])

array([3, 4, 5, 6, 7, 8])

In [ ]:
np.array([3,4,56,56.78,24.4])

array([ 3.  ,  4.  , 56.  , 56.78, 24.4 ])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.linspace(2,50)#linearspace

array([ 2.        ,  2.97959184,  3.95918367,  4.93877551,  5.91836735,
        6.89795918,  7.87755102,  8.85714286,  9.83673469, 10.81632653,
       11.79591837, 12.7755102 , 13.75510204, 14.73469388, 15.71428571,
       16.69387755, 17.67346939, 18.65306122, 19.63265306, 20.6122449 ,
       21.59183673, 22.57142857, 23.55102041, 24.53061224, 25.51020408,
       26.48979592, 27.46938776, 28.44897959, 29.42857143, 30.40816327,
       31.3877551 , 32.36734694, 33.34693878, 34.32653061, 35.30612245,
       36.28571429, 37.26530612, 38.24489796, 39.2244898 , 40.20408163,
       41.18367347, 42.16326531, 43.14285714, 44.12244898, 45.10204082,
       46.08163265, 47.06122449, 48.04081633, 49.02040816, 50.        ])

In [ ]:
np.linspace(2,25)

array([ 2.        ,  2.46938776,  2.93877551,  3.40816327,  3.87755102,
        4.34693878,  4.81632653,  5.28571429,  5.75510204,  6.2244898 ,
        6.69387755,  7.16326531,  7.63265306,  8.10204082,  8.57142857,
        9.04081633,  9.51020408,  9.97959184, 10.44897959, 10.91836735,
       11.3877551 , 11.85714286, 12.32653061, 12.79591837, 13.26530612,
       13.73469388, 14.20408163, 14.67346939, 15.14285714, 15.6122449 ,
       16.08163265, 16.55102041, 17.02040816, 17.48979592, 17.95918367,
       18.42857143, 18.89795918, 19.36734694, 19.83673469, 20.30612245,
       20.7755102 , 21.24489796, 21.71428571, 22.18367347, 22.65306122,
       23.12244898, 23.59183673, 24.06122449, 24.53061224, 25.        ])

In [ ]:
np.linspace(2,25,10, retstep=True)

(array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
        14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ]),
 2.5555555555555554)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.ones(5,dtype=np.int)

<ipython-input-104-8516034fbf9d>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones(5,dtype=np.int)


array([1, 1, 1, 1, 1])

In [ ]:
np.random.random()

0.4822804613226338

In [ ]:
np.random.random(5)

array([0.34777335, 0.98087484, 0.21403967, 0.98471026, 0.55153417])

In [ ]:
np.random.random([4,4])

array([[0.80513492, 0.19305262, 0.72709408, 0.20236118],
       [0.55871445, 0.81763383, 0.24315036, 0.07158598],
       [0.28095383, 0.08700133, 0.54432691, 0.38935656],
       [0.02119779, 0.8172643 , 0.48938155, 0.13612718]])

In [ ]:
np.random.randint(1,100)

90

In [ ]:
np.random.randint(1,100,[4,5])

array([[27, 98, 18, 36, 50],
       [57, 24, 49, 93, 90],
       [35, 77, 38, 71, 71],
       [66, 10, 35, 34, 53]])

In [ ]:
x[0][0]
     

TypeError: ignored

In [ ]:
x

10

In [ ]:
x=np.random.randint(1,100,10)

In [ ]:
x

array([56, 12, 36, 63, 93, 90, 51, 29, 47, 79])

In [ ]:
x[0]

56

In [ ]:
x[-1]

79

In [ ]:
x[0:5]

array([56, 12, 36, 63, 93])

In [ ]:
x[:]

array([56, 12, 36, 63, 93, 90, 51, 29, 47, 79])

In [ ]:
y=np.random.randint(1,100,[4,6])

In [ ]:
y

array([[50, 99, 21, 27, 87, 37],
       [79, 23, 75, 68, 81, 30],
       [14,  6, 99,  7, 54, 87],
       [69, 13, 19, 23, 91, 82]])

In [ ]:
y[0][0]

50

In [ ]:
y[:,:]

array([[50, 99, 21, 27, 87, 37],
       [79, 23, 75, 68, 81, 30],
       [14,  6, 99,  7, 54, 87],
       [69, 13, 19, 23, 91, 82]])

In [ ]:
y[:,0]

array([50, 79, 14, 69])

In [ ]:
y[:,0:1]

array([[50],
       [79],
       [14],
       [69]])

In [ ]:
y[0,0]

50

In [ ]:
y[0:2,0:2]

array([[50, 99],
       [79, 23]])

In [ ]:
y


array([[50, 99, 21, 27, 87, 37],
       [79, 23, 75, 68, 81, 30],
       [14,  6, 99,  7, 54, 87],
       [69, 13, 19, 23, 91, 82]])

In [ ]:
y[[0,2],[0,2]]

array([50, 99])

In [ ]:
y[:,[0,2,4]]

array([[50, 21, 87],
       [79, 75, 81],
       [14, 99, 54],
       [69, 19, 91]])

In [ ]:
np.shape(y)

(4, 6)

In [ ]:
np.ndim(y)

2

In [ ]:
np.shape(x)

(10,)

In [ ]:
np.ndim(x)

1

In [ ]:
y=y.flatten()

In [ ]:
y

array([50, 99, 21, 27, 87, 37, 79, 23, 75, 68, 81, 30, 14,  6, 99,  7, 54,
       87, 69, 13, 19, 23, 91, 82])

In [ ]:
np.min(y)

6

In [ ]:
np.max(y)

99

In [ ]:
np.sort(y)

array([ 6,  7, 13, 14, 19, 21, 23, 23, 27, 30, 37, 50, 54, 68, 69, 75, 79,
       81, 82, 87, 87, 91, 99, 99])

In [ ]:
np.argmax(y)

1

In [ ]:
np.argmin(y)

13

In [ ]:
y=np.sort(y)

In [ ]:
y

array([ 6,  7, 13, 14, 19, 21, 23, 23, 27, 30, 37, 50, 54, 68, 69, 75, 79,
       81, 82, 87, 87, 91, 99, 99])

In [ ]:
#mutable h
y[0]
y[0]=100
y

array([100,   7,  13,  14,  19,  21,  23,  23,  27,  30,  37,  50,  54,
        68,  69,  75,  79,  81,  82,  87,  87,  91,  99,  99])

In [ ]:
np.sort(y)

array([  7,  13,  14,  19,  21,  23,  23,  27,  30,  37,  50,  54,  68,
        69,  75,  79,  81,  82,  87,  87,  91,  99,  99, 100])

In [ ]:
np.sum(y)

1335

In [ ]:
np.mean(y)

55.625

In [ ]:
np.median(y)

61.0

In [ ]:
np.std(y)

31.61330482038641

In [ ]:
np.var(y)

999.4010416666666

In [ ]:
y=np.reshape(y,(6,4))

In [ ]:
y

array([[100,   7,  13,  14],
       [ 19,  21,  23,  23],
       [ 27,  30,  37,  50],
       [ 54,  68,  69,  75],
       [ 79,  81,  82,  87],
       [ 87,  91,  99,  99]])

In [ ]:
y=np.reshape(y,(4,-1))

In [ ]:
y

array([[100,   7,  13,  14,  19,  21],
       [ 23,  23,  27,  30,  37,  50],
       [ 54,  68,  69,  75,  79,  81],
       [ 82,  87,  87,  91,  99,  99]])

In [ ]:
np.max(y)

100

In [ ]:
np.max(y,axis=0)#column ka max

array([100,  87,  87,  91,  99,  99])

In [ ]:
np.max(y,axis=1)#row ka max deta h)

array([100,  50,  81,  99])

In [ ]:
z=np.array([[2,4,5,2,55,2]])
np.vstack((y,z))#vertically data stack ho rha h

array([[ 2,  4,  5,  2, 55,  2],
       [ 2,  4,  5,  2, 55,  2]])

In [ ]:
#z=np.array([[2],[4],[5],[55],[2]])
#np.hstack((y,z)) 

In [ ]:
np.vstack((y,[2,3,4,5,66,5]))

array([[ 2,  4,  5,  2, 55,  2],
       [ 2,  3,  4,  5, 66,  5]])

In [ ]:
y

array([[ 2,  4,  5,  2, 55,  2]])

In [ ]:
x

array([56, 12, 36, 63, 93, 90, 51, 29, 47, 79])

In [ ]:
z=np.random.randint(1,100,[5,6])

In [ ]:
z

array([[50, 24, 65, 83, 98, 96],
       [70, 68, 76, 30, 25, 21],
       [ 1, 21, 12, 33, 18, 29],
       [53, 73, 97, 46, 14, 70],
       [63,  1, 28, 51, 78, 86]])

In [ ]:
np.vstack((z,[2,4,5,2,55,2]))

array([[50, 24, 65, 83, 98, 96],
       [70, 68, 76, 30, 25, 21],
       [ 1, 21, 12, 33, 18, 29],
       [53, 73, 97, 46, 14, 70],
       [63,  1, 28, 51, 78, 86],
       [ 2,  4,  5,  2, 55,  2]])

In [ ]:
#np.hstack((z,[5,8,56,3,9]))

ValueError: ignored

In [ ]:
r=np.array([[2],[4],[6],[7],[3]])
np.hstack((z,r))

array([[50, 24, 65, 83, 98, 96,  2],
       [70, 68, 76, 30, 25, 21,  4],
       [ 1, 21, 12, 33, 18, 29,  6],
       [53, 73, 97, 46, 14, 70,  7],
       [63,  1, 28, 51, 78, 86,  3]])

how to check time and space

In [ ]:
import sys

In [ ]:
sys.getsizeof([])#empty list kitna size le rhi h

56

In [ ]:
sys.getsizeof(np.array([]))#np array kitna size le rha h

112

In [ ]:
sys.getsizeof([5])#ek element se 8bite ka size bdhaya list m

64

In [ ]:
sys.getsizeof(np.array([5]))#same 8bite bdhaya

120

In [ ]:
#size inc. krne k liy
sys.getsizeof([i for i in range(100)])

920

In [ ]:
sys.getsizeof(np.array([i for i in range(100)]))#ab array size km le rha h it takes 4 bite 

912

In [ ]:
import time

In [ ]:
x=list(range(1,4))
y=list(range(1,4))
z=[]
start=time.time()
for i in range(len(x)):
  z.append(x[i]+y[i])
  end=time.time()
  total=end-start
  print("total time taken is:",total) 

total time taken is: 9.655952453613281e-05
total time taken is: 0.0001957416534423828
total time taken is: 0.00024056434631347656


In [ ]:
#list n jyda time liya h nd array n km time leta h

**PANDAS**

In [ ]:
import pandas as pd

In [ ]:
pd.Series([2,1,3,4,5,6,7,7,4])

0    2
1    1
2    3
3    4
4    5
5    6
6    7
7    7
8    4
dtype: int64

In [ ]:
pd.Series([2,1,3,5],index=['A','B','C','D'])

A    2
B    1
C    3
D    5
dtype: int64

In [ ]:
import numpy as np

In [ ]:
age=np.random.randint(18,50,70)
Series=pd.Series(age)

In [ ]:
Series[0]

23

In [ ]:
Series[0:5]

0    23
1    29
2    28
3    45
4    24
dtype: int64

In [ ]:
Series.head()

0    23
1    29
2    28
3    45
4    24
dtype: int64

In [ ]:
Series.tail()

65    45
66    34
67    27
68    29
69    47
dtype: int64

In [ ]:
Series.tail(2)

68    29
69    47
dtype: int64

In [ ]:
Series.mean()

34.785714285714285

In [ ]:
data={
    "names":["john","mac","sam","nick","peter","tim"],
    "sal":[4500,6500,8700,5500,3400,3200],
    "dept":["it","it","hr","hr","it","hr"]
}

In [ ]:
df=pd.DataFrame(data,index=['e1','e2','e3','e4','e5','e6'])

In [ ]:
df

names   sal dept
e1   john  4500   it
e2    mac  6500   it
e3    sam  8700   hr
e4   nick  5500   hr
e5  peter  3400   it
e6    tim  3200   hr

In [ ]:
df.shape

(6, 3)

In [ ]:
df.columns

Index(['names', 'sal', 'dept'], dtype='object')

In [ ]:
df.head()

names   sal dept
0   john  4500   it
1    mac  6500   it
2    sam  8700   hr
3   nick  5500   hr
4  peter  3400   it

In [ ]:
df['names']

0     john
1      mac
2      sam
3     nick
4    peter
5      tim
Name: names, dtype: object

In [ ]:
df.loc[0]

names    john
sal      4500
dept       it
Name: 0, dtype: object

In [ ]:
df.loc['e1']

names    john
sal      4500
dept       it
Name: e1, dtype: object

In [ ]:
df.iloc[0:3]

names   sal dept
e1  john  4500   it
e2   mac  6500   it
e3   sam  8700   hr

In [ ]:
df.names

e1     john
e2      mac
e3      sam
e4     nick
e5    peter
e6      tim
Name: names, dtype: object

In [ ]:
df['sal']>500

e1    True
e2    True
e3    True
e4    True
e5    True
e6    True
Name: sal, dtype: bool

In [ ]:
df[df['sal']>5000]

names   sal dept
e2   mac  6500   it
e3   sam  8700   hr
e4  nick  5500   hr

In [ ]:
df[df['dept']=='it']

names   sal dept
e1   john  4500   it
e2    mac  6500   it
e5  peter  3400   it